
/**
 * Represents a single sleep cycle within a sleep record.
 */
export interface SleepCycle {
  /** Unique identifier for the sleep cycle, usually generated by Firestore or frontend. */
  id: string;
  /** Time the baby was put to bed, in HH:MM format. */
  bedtime: string;
  /** Duration it took for the baby to fall asleep (e.g., "15 דקות", "מייד"). */
  timeToSleep: string;
  /** Person who put the baby to sleep (e.g., "אמא", "אבא", "לבד"). */
  whoPutToSleep: string;
  /** Description of how the baby fell asleep. */
  howFellAsleep: string;
  /** Time the baby woke up, in HH:MM format. Optional. */
  wakeTime?: string;
}

/**
 * Represents a collection of sleep cycles for a specific date.
 */
export interface SleepRecord {
  /** Unique identifier for the sleep record, usually generated by Firestore. */
  id: string;
  /** Date of the sleep record, in YYYY-MM-DD format. */
  date: string;
  /** Array of sleep cycles for this record. */
  sleepCycles: SleepCycle[];
  /** Timestamp of when the record was created or last updated. */
  timestamp?: any; // Firestore Timestamp type
}

/**
 * Represents a baby's profile and associated data.
 */
export interface Baby {
  /** Unique identifier for the baby, generated by Firestore. */
  id: string;
  /** Baby's first name. */
  name: string;
  /** Baby's family name. */
  familyName: string;
  /** Age of the baby in months. */
  age: number;
  /** Mother's name. */
  motherName: string;
  /** Father's name. */
  fatherName: string;
  /** Number of siblings the baby has. */
  siblingsCount: number;
  /** Optional string listing names and ages of siblings. */
  siblingsNames?: string;
  /** Optional general description about the baby. */
  description?: string;
  /** Username for parents. Used to link to parent view and for querying. Should be unique. */
  parentUsername: string;
  /** UID of the parent from Firebase Auth, if known/linked. Optional for initial setup. */
  parentAuthUid?: string;
  /** Notes from the sleep consultant, visible to parents. */
  coachNotes?: string;
  /** Flag indicating if the baby's profile is archived. */
  isArchived: boolean;
  /** ISO Date string representing when the baby was archived. Null if not archived. */
  dateArchived?: string | null;
  /** ISO Date string of the last modification to the baby's record. */
  lastModified: string;
  /** UID of the coach who created/manages this baby. Optional. */
  coachAuthUid?: string;
}

/**
 * Type definition for data used when adding a new baby.
 * Excludes fields that are auto-generated or managed by Firestore.
 */
export type BabyFormData = {
  name: string;
  familyName: string;
  age: number;
  motherName: string;
  fatherName: string;
  siblingsCount: number;
  siblingsNames?: string;
  description?: string;
  parentUsername: string;
  coachNotes?: string;
};

/**
 * Type definition for the data structure used in the sleep record form.
 */
export type SleepRecordFormData = {
  date: Date; // Date object from calendar input
  sleepCycles: Array<Omit<SleepCycle, 'id'> & { id?: string }>; // id is optional for new cycles
};
