import type { Timestamp } from 'firebase/firestore';

/**
 * Represents a single sleep cycle within a sleep record.
 */
export interface SleepCycle {
  /** Unique identifier for the sleep cycle, usually generated by Firestore or frontend. */
  id: string;
  /** Time the baby was put to bed, in HH:MM format. */
  bedtime: string;
  /** Duration it took for the baby to fall asleep (e.g., "15 דקות", "מייד"). */
  timeToSleep: string;
  /** Person who put the baby to sleep (e.g., "אמא", "אבא", "לבד"). */
  whoPutToSleep: string;
  /** Description of how the baby fell asleep. */
  howFellAsleep: string;
  /** Time the baby woke up, in HH:MM format. Optional. */
  wakeTime?: string;
}

/**
 * Represents a collection of sleep cycles for a specific date.
 */
export interface SleepRecord {
  /** Unique identifier for the sleep record, usually generated by Firestore. */
  id: string;
  /** Date of the sleep record, in YYYY-MM-DD format. */
  date: string;
  /** Array of sleep cycles for this record. */
  sleepCycles: SleepCycle[];
  /** Timestamp of when the record was created or last updated. */
  timestamp?: Timestamp; // Firestore Timestamp type
}

/**
 * Represents a baby's profile and associated data.
 */
export interface Baby {
  /** Unique identifier for the baby, generated by Firestore. This ID is typically the `parentUsername` from the invite. */
  id: string;
  /** Baby's first name. */
  name: string;
  /** Baby's family name. */
  familyName: string;
  /** Age of the baby in months. */
  age: number;
  /** Mother's name. */
  motherName: string;
  /** Father's name. */
  fatherName: string;
  /** Number of siblings the baby has. */
  siblingsCount: number;
  /** Optional string listing names and ages of siblings. */
  siblingsNames?: string;
  /** Optional general description about the baby. */
  description?: string;
  /** Unique username for the baby's profile, used as the document ID and for routing. */
  parentUsername: string;
  /** Array of Firebase Auth UIDs of the linked parents. */
  parentIds: string[];
  /** Notes from the sleep consultant, visible to parents. */
  coachNotes?: string;
  /** Flag indicating if the baby's profile is archived. */
  isArchived: boolean;
  /** ISO Date string representing when the baby was archived. Null if not archived. */
  dateArchived?: string | null;
  /** ISO Date string of the last modification to the baby's record. */
  lastModified: string;
  /** UID of the coach who created/manages this baby. */
  coachId: string;
  /** The invite code associated with this baby. */
  inviteCode: string;
  /** Sleep records for the baby, often fetched as a subcollection or embedded if small and few. */
  sleepRecords?: SleepRecord[];
}

/**
 * Type definition for data used when adding or editing a baby.
 * Excludes fields that are auto-generated or managed by Firestore.
 */
export type BabyFormData = {
  name: string;
  familyName: string;
  age: number;
  motherName: string;
  fatherName: string;
  siblingsCount: number;
  siblingsNames?: string;
  description?: string;
  coachNotes?: string;
  parentEmail1?: string;
  parentEmail2?: string;
  inviteCode?: string;
  parentUsername?: string;
};

/**
 * Type definition for the data structure used in the sleep record form.
 */
export type SleepRecordFormData = {
  date: Date; // Date object from calendar input
  sleepCycles: Array<Omit<SleepCycle, 'id'> & { id?: string }>; // id is optional for new cycles
};

/**
 * Represents an invite document in Firestore.
 */
export interface Invite {
  /** Document ID, which is the unique invite code. */
  id: string;
  /** UID of the coach who created the invite. */
  coachId: string;
  /** Data for the baby to be created/linked. If this is null/undefined, it's a coach invite. */
  babyData?: BabyFormData;
  /** Array of email addresses of the intended users. Can be empty. */
  parentEmails: string[];
  /** Array of email addresses for coach invites. */
  invitedEmails?: string[];
  /** Status of the invite. */
  status: 'pending' | 'partially_redeemed' | 'completed' | 'expired' | 'revoked';
  /** Array of users who have redeemed this invite. */
  usedBy: Array<{
    userId: string; // Firebase Auth UID of the user
    email: string;  // Email of the user
    redeemedAt: Timestamp;
  }>;
  /** Timestamp of when the invite was created. */
  createdAt: Timestamp;
  /** Timestamp of when the invite expires (e.g., 30 days from creation). */
  expiresAt: Timestamp;
  /** Array of placeholder user IDs created for this invite. */
  placeholderUserIds?: string[];
}

/**
 * Defines the roles a user can have within the application.
 */
export type UserRole = 'admin' | 'coach' | 'parent';

/**
 * Represents a user document in the 'users' collection. This is the single source of truth for user identity.
 */
export interface User {
  /** The user's unique Firebase Authentication UID. This is the document ID. */
  id: string;
  /** The user's primary email address. */
  email: string;
  /** The user's display name. */
  name: string;
  /** The assigned role for the user, which governs their permissions. */
  role: UserRole;
  /** The user's current status (e.g., active, disabled). */
  status: 'active' | 'disabled';
  /** Timestamp of the last login. */
  lastLogin?: Timestamp;
}

/**
 * Represents a coach's profile document in the 'coaches' collection.
 * This stores data specific to a coach's professional activities.
 */
export interface CoachProfile {
  /** The coach's unique Firebase Authentication UID. This is the document ID. */
  id: string;
  /** The number of active clients the coach is currently managing. */
  clientCount: number;
  // Future fields could include: bio, certifications, etc.
}

/**
 * Represents a parent's profile document in the 'parents' collection.
 * This can be expanded with parent-specific information in the future.
 */
export interface ParentProfile {
  /** The parent's unique Firebase Authentication UID. This is the document ID. */
  id: string;
  // Future fields could include: communication preferences, etc.
}

/**
 * Log levels for different types of events
 */
export enum LogLevel {
  DEBUG = 'debug',
  INFO = 'info',
  WARN = 'warn',
  ERROR = 'error',
  CRITICAL = 'critical'
}

/**
 * Event categories for audit trails
 */
export enum EventCategory {
  AUTHENTICATION = 'authentication',
  USER_MANAGEMENT = 'user_management',
  BABY_MANAGEMENT = 'baby_management',
  SLEEP_DATA = 'sleep_data',
  INVITATION = 'invitation',
  SYSTEM = 'system',
  SECURITY = 'security',
  PERFORMANCE = 'performance'
}

/**
 * Base log entry interface
 */
export interface LogEntry {
  timestamp: Date;
  level: LogLevel;
  message: string;
  category?: EventCategory;
  userId?: string;
  userEmail?: string;
  userRole?: string;
  sessionId?: string;
  ipAddress?: string;
  userAgent?: string;
  metadata?: Record<string, any>;
  error?: {
    name: string;
    message: string;
    stack?: string;
  };
}

/**
 * Audit event types for detailed tracking
 */
export enum AuditEventType {
  // Authentication events
  LOGIN_SUCCESS = 'login_success',
  LOGIN_FAILED = 'login_failed',
  LOGOUT = 'logout',
  PASSWORD_RESET_REQUEST = 'password_reset_request',
  PASSWORD_RESET_SUCCESS = 'password_reset_success',
  SIGNUP_SUCCESS = 'signup_success',
  SIGNUP_FAILED = 'signup_failed',
  
  // User management events
  USER_CREATED = 'user_created',
  USER_UPDATED = 'user_updated',
  USER_DELETED = 'user_deleted',
  ROLE_ASSIGNED = 'role_assigned',
  ROLE_CHANGED = 'role_changed',
  
  // Baby management events
  BABY_CREATED = 'baby_created',
  BABY_UPDATED = 'baby_updated',
  BABY_ARCHIVED = 'baby_archived',
  BABY_RESTORED = 'baby_restored',
  BABY_DELETED = 'baby_deleted',
  
  // Sleep data events
  SLEEP_RECORD_CREATED = 'sleep_record_created',
  SLEEP_RECORD_UPDATED = 'sleep_record_updated',
  SLEEP_RECORD_DELETED = 'sleep_record_deleted',
  
  // Invitation events
  INVITATION_CREATED = 'invitation_created',
  INVITATION_REDEEMED = 'invitation_redeemed',
  INVITATION_CANCELLED = 'invitation_cancelled',
  INVITATION_EXPIRED = 'invitation_expired',
  
  // System events
  DATA_EXPORT = 'data_export',
  BULK_OPERATION = 'bulk_operation',
  SYSTEM_ERROR = 'system_error',
  
  // Security events
  UNAUTHORIZED_ACCESS = 'unauthorized_access',
  PERMISSION_DENIED = 'permission_denied',
  SUSPICIOUS_ACTIVITY = 'suspicious_activity'
}

/**
 * Audit log entry interface for sensitive operations
 */
export interface AuditLogEntry extends LogEntry {
  eventType: AuditEventType;
  resourceId?: string;
  resourceType?: string;
  oldValue?: any;
  newValue?: any;
  success: boolean;
  duration?: number;
}

/**
 * Performance metrics interface
 */
export interface PerformanceMetric {
  timestamp: Date;
  operation: string;
  duration: number;
  userId?: string;
  metadata?: Record<string, any>;
}
